# Generated by Django 5.0.3 on 2024-07-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hashtags',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
