# Generated by Django 5.0.6 on 2024-07-02 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_date_of_birth_customuser_end_year_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='job_position',
            new_name='job_type',
        ),
    ]
