# Generated by Django 5.0.3 on 2024-07-03 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_job_position_customuser_job_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='national_id',
        ),
    ]
